EcommerceProject_Webbuy/Models/ViewModel/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceProject_Webbuy.Models.ViewModel
{
    public class ProductListViewModel
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public int Price { get; set; }
        public string SubCategory_Name { get; set; }
        public string Brand_Name { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Product_Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }   
        //public DateTime UpdatedDate { get; set; }
    }

    public class ProductCreateViewModel
    {
        public string Product_Name { get; set; }
        public int? Price { get; set; }
        public int SubCategory_ID { get; set; }
        public List<SelectListItem> Categories { get; set; }
        public List<SelectListItem> SubCategories { get; set; }
        public int Brand_ID { get; set; }
        public List<SelectListItem> Brands { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Product_Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string Description { get; set; }
        public int? Quantity { get; set; }       
        
    }

    public class ProductEditViewModel
    {
        [Key]
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public int? Price { get; set; }
        public int Category_ID { get; set; }
        public List<SelectListItem> Categories { get; set; }
        public int SubCategory_ID { get; set; }
        public List<SelectListItem> SubCategories { get; set; }
        public int Brand_ID { get; set; }
        public List<SelectListItem> Brands { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Product_Image  { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string Description { get; set; }
        public int? Quantity { get; set; }
    }

    public class ProductDetailsViewModel
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string Description { get; set; }

    }
}

EcommerceProject_Webbuy/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EcommerceProject_Webbuy.Models.DAL;
using EcommerceProject_Webbuy.Models.DataObjects;
using EcommerceProject_Webbuy.Models.ViewModel;
using Microsoft.AspNet.Identity;

namespace EcommerceProject_Webbuy.Controllers
{
    public class CartController : Controller
    {
        CartManagement cartManagement = new CartManagement();
        public ActionResult Index()
        {
            List<CartDO> records = cartManagement.GetAllRecordsInCart();

            var query = from p in records
                        select new CartViewModel
                        {
                            Cart_ID = p.Cart_ID,
                            User_ID = p.User_ID
                        };

            return View(query.ToList());

        }

        public ActionResult AddToCart(int id, CartAddViewModel model)
        {
            CartDO cartDO = new CartDO();
            if (User.Identity.IsAuthenticated)
            {
                cartDO.User_ID = User.Identity.GetUserId();
                //checking if user already has cart created
                cartDO = cartManagement.GetCartByUserID(cartDO.User_ID);
                if(cartDO.Cart_ID == 0)
                {
                    try
                    {
                        cartDO.User_ID = User.Identity.GetUserId();
                        cartDO.Cart_ID = model.Cart_ID;
                        CartManagement cartManagement = new CartManagement();
                        cartManagement.AddCartIDandUserIDInCart(cartDO);

                        return RedirectToAction("Index");
                    }


                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                    }
                    
                }
                else
                {
                    return RedirectToAction("Index");
                }
                
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

            return null;
        }
    }

}

EcommerceProject_Webbuy/Controllers/ProductController.cs
using EcommerceProject_Webbuy.Models.DAL;
using EcommerceProject_Webbuy.Models.DataObjects;
using EcommerceProject_Webbuy.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace EcommerceProject_Webbuy.Controllers
{
    public class ProductController : Controller
    {
        ProductManagement productManagement = new ProductManagement();
        // GET: Product
        public ActionResult Index()
        {
            List<ProductDO> products = productManagement.GetAllProducts();

            var query = from p in products
                        select new ProductListViewModel
                        {
                            Product_ID = p.Product_ID,
                            Product_Name = p.Product_Name,
                            Price = Convert.ToInt32(p.Price),
                            SubCategory_Name = p.SubCategory.SubCategory_Name,
                            Brand_Name = p.Brand.Brand_Name,
                            Size = p.Size,
                            Color = p.Color,
                            Product_Image = p.Product_Image, 
                            //ImageFile = "\\Images" + "\\" + p.Product_Image.ToString(),
                            Description = p.Description,
                            Quantity = Convert.ToInt32(p.Quantity),
                            //UpdatedDate = Convert.ToDateTime(p.UpdatedDate)
                        };

            return View(query.ToList());

        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            ProductManagement productManagement = new ProductManagement();
            ProductDO model = productManagement.GetProductByID(id);
            ProductDetailsViewModel details = new ProductDetailsViewModel();
            details.Product_ID = model.Product_ID;
            details.Product_Name = model.Product_Name;
            details.Product_Image = model.Product_Image;
            details.Description = model.Description;
            return View(details);
        }

        private List<SelectListItem> getBrandDropDownData()
        {
            BrandManagement brandManagement = new BrandManagement();

            var query = from b in brandManagement.GetAllBrands()
                        select new SelectListItem
                        {
                            Value = b.Brand_ID.ToString(),
                            Text = b.Brand_Name
                        };
            return query.ToList();
        }

        private List<SelectListItem> getSubCategoryDropDownData()
        {
            SubCategoryManagement subCategoryManagement = new SubCategoryManagement();

            var query = from cat in subCategoryManagement.GetAllSubCategory()
                        select new SelectListItem
                        {
                            Value = cat.SubCategory_ID.ToString(),
                            Text = cat.SubCategory_Name
                        };
            return query.ToList();
        }

        private List<SelectListItem> GetCategoryDropdownData()
        {
            CategoryManagement categoryManagement = new CategoryManagement();

            var query = from cat in categoryManagement.GetAllCategory()
                        select new SelectListItem
                        {
                            Value = cat.Category_ID.ToString(),
                            Text = cat.Category_Name
                        };

            return query.ToList();
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ProductCreateViewModel model = new ProductCreateViewModel();
            model.Brands = getBrandDropDownData();
            model.Categories = GetCategoryDropdownData();

            model.SubCategories = new List<SelectListItem>()
            {
                new SelectListItem
                {
                    Value = "0",
                    Text = "-Select SubCategory"
                }
            };
            return View(model);
        }

        public ActionResult getSubCategory(int Category_ID)
        {
            SubCategoryManagement subCategoryManagement = new SubCategoryManagement();

            var query = from subCategory in subCategoryManagement.GetSubCategoryByCategoryID(Category_ID)
                        select new SelectListItem
                        {
                            Value = subCategory.SubCategory_ID.ToString(),
                            Text = subCategory.SubCategory_Name
                        };
            List<SelectListItem> SubCategories = query.ToList();

            return Json(SubCategories, JsonRequestBehavior.AllowGet);
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(ProductCreateViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                ProductDO dataModel = new ProductDO();
                dataModel.Product_Name = model.Product_Name;
                dataModel.Price = model.Price;
                dataModel.SubCategory_ID = model.SubCategory_ID;
                dataModel.Brand_ID = model.Brand_ID;
                dataModel.Size = model.Size;
                dataModel.Color = model.Color;

                //string FileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                string FileName = Path.GetFileName(model.ImageFile.FileName);
                //string FileExtension = Path.GetExtension(model.ImageFile.FileName);
                string UploadPath = ConfigurationManager.AppSettings["ImagesPath"].ToString();
                model.Product_Image = UploadPath + FileName;
                model.ImageFile.SaveAs(Server.MapPath((model.Product_Image)));

                dataModel.Product_Image = model.Product_Image;
                //dataModel.ImageFile = model.ImageFile;
                dataModel.Description = model.Description;
                dataModel.Quantity = model.Quantity;
                
                
                ProductManagement productManagement = new ProductManagement();
                productManagement.InsertProduct(dataModel);


                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                model.Categories = GetCategoryDropdownData();
                return View(model);
            }
        }
        

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            ProductManagement productManagement = new ProductManagement();
            ProductDO modelData = productManagement.GetProductByID(id);

            ProductEditViewModel model = new ProductEditViewModel();
            model.Product_ID = modelData.Product_ID;
            model.Product_Name = modelData.Product_Name;
            model.Price = modelData.Price;

           // model.Category_ID = modelData.Category_ID;
            model.Categories = GetCategoryDropdownData();

            model.SubCategory_ID = modelData.SubCategory_ID;
            model.SubCategories = getSubCategoryDropDownData();

            model.Brand_ID = modelData.Brand_ID;
            model.Brands = getBrandDropDownData();

            model.Size = modelData.Size;
            model.Color = modelData.Color;
            model.Product_Image = modelData.Product_Image;
            model.Description = modelData.Description;
            model.Quantity = modelData.Quantity;

            TempData["ImagesPath"] = model.Product_Image;

            return View(model);
            
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id,ProductEditViewModel model, HttpPostedFileBase ImageFile)
        {
            
            try
            {
                // TODO: Add update logic here
                ProductDO dataModel = new ProductDO();
                dataModel.Product_ID = model.Product_ID;
                dataModel.Product_Name = model.Product_Name;
                dataModel.Price = model.Price;      
                //dataModel.Category_ID = model.Category_ID;
                dataModel.SubCategory_ID = model.SubCategory_ID;
                dataModel.Brand_ID = model.Brand_ID;
                dataModel.Size = model.Size;
                dataModel.Color = model.Color;
                    

                if (ImageFile == model.ImageFile)
                {
                    dataModel.Product_Image = TempData["ImagesPath"].ToString();
                    //dataModel.Product_Image = model.Product_Image;
                    dataModel.Description = model.Description;
                    dataModel.Quantity = model.Quantity;

                    ProductManagement productManagement = new ProductManagement();
                    productManagement.EditProduct(dataModel);

                    return RedirectToAction("Index");
                }
                else
                {
                    string FileName = Path.GetFileName(model.ImageFile.FileName);
                    string UploadPath = ConfigurationManager.AppSettings["ImagesPath"].ToString();
                    model.Product_Image = UploadPath + FileName;
                    model.ImageFile.SaveAs(Server.MapPath((model.Product_Image)));
                    dataModel.Product_Image = model.Product_Image;
                    dataModel.Description = model.Description;
                    dataModel.Quantity = model.Quantity;

                    ProductManagement productManagement = new ProductManagement();
                    productManagement.EditProduct(dataModel);

                    return RedirectToAction("Index");
                }
                //dataModel.Product_Image = model.Product_Image;
                
                
            }
            catch(Exception e)
            {

EcommerceProject_Webbuy/Views/Product/Create.cshtml
@model EcommerceProject_Webbuy.Models.ViewModel.ProductCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductCreateViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Categories, Model.Categories, "-Select Category-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubCategory_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubCategory_ID, Model.SubCategories, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubCategory_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Brand_ID, Model.Brands, "-Select Brand-", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#Categories").change(function () {
                var CatID = $("#Categories").val();
                $.ajax({
                    url: "/Product/getSubcategory",
                    data: { "Category_ID": CatID },
                    contentType: "application/json",
                    type: "get",
                    success: function (results) {
                        var subCategory = $("#SubCategory_ID");
                        subCategory.empty();
                        subCategory.append("<option value=0>-Select SubCategory-</option>");
                        $.each(results, function (index, sc) {
                            subCategory.append("<option value= " + sc.Value + ">" + sc.Text + "</option>");
                        })
                    }
                })
            })
        })
    </script>
}

EcommerceProject_Webbuy/Views/Product/Details.cshtml
@model EcommerceProject_Webbuy.Models.ViewModel.ProductDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<html>
<head>
    <link rel="stylesheet" href="~/Content/style.css">
</head>

<h2>Details</h2>

<div>
    <h4>ProductDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Image)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Product_Image)*@
            <img src="@Url.Content(Model.Product_Image)" alt="not visible" width="230" height="230" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>


        @*@Html.ActionLink("Add To Cart", "AddToCart", new { id = Model.Product_ID }, "Cart")*@
        @Html.ActionLink("Add To Cart", "AddToCart", "Cart", new { id=Model.Product_ID }, null)
        @*<a href="@Html.ActionLink("Add To Cart", "AddToCart", "CartController", new {  id=Model.Product_ID  })" class="btn">Add To Cart</a>*@
        @*<input type="button" value="Add To Cart" class="btn" onclick="location.href='@Url.Action("AddToCart", "CartController", new { id = Model.Product_ID }) '" />*@

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>
</html>

EcommerceProject_Webbuy/Views/Product/Edit.cshtml
@model EcommerceProject_Webbuy.Models.ViewModel.ProductEditViewModel

@{
    ViewBag.Title = "Edit";
}



<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductEditViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Product_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Categories, Model.Categories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubCategory_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubCategory_ID, Model.SubCategories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubCategory_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Brand_ID, Model.Brands, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.Product_Image)" alt="not visible" width="230" height="230" />
                <input type="file" name="ImageFile" />
                
                @*@Html.EditorFor(model => model.Product_Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Product_Image, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    $(document).ready(function () {
        $("#Categories").change(function () {
            var CatID = $("#Categories").val();
            $.ajax({
                url: "/Product/getSubcategory",
                data: { "Category_ID": CatID },
                contentType: "application/json",
                type: "get",
                success: function (results) {
                    var subCategory = $("#SubCategory_ID");
                    subCategory.empty();
                    subCategory.append("<option value=0>-Select SubCategory-</option>");
                    $.each(results, function (index, sc) {
                        subCategory.append("<option value= " + sc.Value + ">" + sc.Text + "</option>");
                    })
                }
            })
        })
    })
</script>
}

EcommerceProject_Webbuy/Views/Product/Index.cshtml
@model IEnumerable<EcommerceProject_Webbuy.Models.ViewModel.ProductListViewModel>

@{
    ViewBag.Title = "Index";
    int counter = 0;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title All Products - Modern Living </title>
    <link rel="stylesheet" href="~/Content/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <div class="row">
        @foreach (var item in Model)
        {
            if (counter != 0 && counter % 3 == 0)
            {
            @:</div>
            @:<div class="row">
            }

            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="@Url.Content(item.Product_Image)" alt="not visible" data-holder-rendered="true" style="height: 200px; width: 100%; display: block;" />
                    <div class="caption">
                        <h3 id="thumbnail-label">@Html.DisplayFor(modelItem => item.Product_Name)</h3>
                        <p>Rs @Html.DisplayFor(modelItem => item.Price)</p>
                        <br />
                        <p>@Html.ActionLink("Details", "Details", new {  id=item.Product_ID  })</p>
                    </div>
                </div>
            </div>

            counter++;
        }
    </div>
   
</body>
</html>